### ISSUE TITLE
Trying to add functions

### ISSUE THREAD

**Issue by thmsmlt** [vargaradu/UA-Midi-Control#4]
Hi,

First of all: great app, I wish I found it a lot sooner.

I have been trying to add some functionality to this app using the Xcode project, but being new at this I am running into a few (probably beginner) errors.

![Screen Shot 2020-05-02 at 16 38 16 1](https://user-images.githubusercontent.com/28437402/80867322-f06d5680-8c93-11ea-9bf4-16305752a23e.png)

![Screen Shot 2020-05-02 at 16 38 26](https://user-images.githubusercontent.com/28437402/80867326-f19e8380-8c93-11ea-9231-5aaab3914a9c.png)

Could anyone give me some directions?

I have succeeded in capturing TCP packets using Wireshark and would like to decode a few more to add functions and to see wether this software can be extended to control LUNA (UA's new DAW), which is just as inaccessible as the UA Console. 

ALTERNATIVELY, I would be massively interested in a very simple version of this app which opens up the TCP connection and let's me send some JSON strings so I can interface with it using AppleScript or something similar... E.g. a text window to put the JSON command into and a button to send it. 

Eventually, I would like to use Keyboard Maestro to capture MIDI packets and run the right JSON script, which is more user friendly and powerful. Any ideas on how to make this happen?

Kind regards,

Thomas

**Comment by raduvarga** [comment]
Hi,

Most likely your problem comes from the fact that you opened the ".xcodeproject", but you need to work on the ".xcworkspace" file to make everything work. I forgot to include it in the documentation initially.
