### ISSUE TITLE
Control headphone volume?

### ISSUE THREAD

**Issue by kyleawayan** [vargaradu/UA-Midi-Control#5]
Thank you for reverse engineering and documenting the UA "API"!

I was just wondering, have you found a way to control the headphone volume? As you probably know, there's no way to change it in the Console app. You could only change the headphone volume with the knob on the device itself.

I've been going through `/devices/{id}/outputs`. I was able to adjust the monitor value through `CRMonitorLevel`, however I couldn't find anything to change the headphone volume level.

**Comment by raduvarga** [comment]
Nope, it's not possible. 
There is however a tested workaround: https://www.reddit.com/r/UaMidiControl/wiki/index#wiki_headphone_volume
